### ISSUE TITLE
Type information missing for types whose BaseType is `referenceTypeModifier`

### ISSUE THREAD

**Issue by halildurmus** [halildurmus/winmd#56]
For example, `PhoneNumberFormatter`'s [TryCreate](https://docs.microsoft.com/en-us/uwp/api/windows.globalization.phonenumberformatting.phonenumberformatter.trycreate?view=winrt-22621) function has an `out` parameter `phoneNumber`. TypeIdentifier returns its baseType as `referenceTypeModifier` but it doesn't have any information regarding its type (`typeIdentifier.type` returns null).

I did some digging and I found this code: https://github.com/timsneath/winmd/blob/b8920329a0882bae60ae061004f27860491c3d5d/lib/src/utils/typetuple.dart#L46-L51

For `phoneNumber` parameter, `signatureBlob[1]` returns `18` (0x12) which equals to `ELEMENT_TYPE_CLASS `. I tried a few things but couldn't figure it out, this is too complex for me. 

Can you take a look at these when you have a chance?

**Comment by timsneath** [comment]
On a flight this afternoon, will take a look at this then!

**Comment by timsneath** [comment]
Fixed in #57 and published as v2.2.1
